README.md

creates readme

---

.babelrc
.eslintrc
.gitignore
package-lock.json
package.json
public/index.html
src/containers/app.jsx
src/index.jsx
src/reducers/data.reducer.js
src/reducers/index.js
src/router.jsx
src/server.js
src/start_server.js
src/store.config.js
webpack.config.js

Create project set up

---

package.json
src/components/nav_bar.jsx
src/containers/app.jsx
src/containers/career.jsx
src/containers/career_details.jsx
src/containers/list.jsx
src/index.jsx
src/router.jsx

also add three links for each menu on navbar relates #16

create nav bar

---

package-lock.json
src/containers/career.jsx

Relates #11
add buttons to career container with like and dislike

add buttons for like and dislike

---

package.json
src/components/career_card.jsx
src/containers/career.jsx
src/reducers/index.js
src/store.config.js

Relates #10
create component for career card with mock data for 2 jobs

add career_card page with map state to props

---

src/components/career_card.jsx
src/containers/career.jsx

Relates #17
Add swipe function to career card container with onTouch React events.
Still needs to change it to render the next job.

Add swipe functionality to career card

---

src/containers/career.jsx

relates #24 
Create a function that moves to the next career when clicking either the like or dislike button

Next career function

---

src/components/career_card.jsx
src/components/career_info.jsx
src/containers/career.jsx

Relates #28
Add the career info component and button info to the career card, to see more info about a job

Add career info component to career card page

---

.eslintrc
src/containers/career.jsx
src/store.config.js

relates #25
when a user clicks like button, the data of liked career will be stored in localstorage

create addToLocal function

---

src/containers/welcome.jsx
src/router.jsx

#45 #46 #47 #48 
add text content and button which redirects to ```/career``` (swiping)

Add content button welcome

---

src/containers/career.jsx
src/containers/list.jsx

relates #33 
Create a list using the information in local storage

Populate list

---

src/store.config.js

Relates #20 
Add data for 5 jobs with: 
- title
- tagline
- description
- degree
- image
- degree
- grade_bagrut
- grade_psychometric
- universities
- salary_start
- salary_ten_year

Add data to store.config file

---

package-lock.json
package.json
public/style.css
src/containers/career.jsx

relates #26  - but it still flipping without clicking the info button

Flipping page

---

package.json
src/containers/career.jsx
src/containers/list.jsx

Relates #60 #61 
Add a function on career card to check if a job is already exists in the array.
Add a function on career card to show only careers that haven't been "liked" before, so the user doesn't need to "like" the jobs again.

Functionality for managing duplicates on page and storage

---

public/index.html
src/components/career_card.jsx
src/components/career_info.jsx
src/components/nav_bar.jsx
src/containers/career.jsx

Relates #18 #27
Here is the design of both the front part and the back part of the career card: 
To avoid having problems with compiling the SASS files to CSS, I styled the career page and navbar, but @Heathercoraje would push all design files, so all can compile to one css file. 
This pull request contains class names on different files for styling with SASS.
I hope it makes sense... :thinking:

Set up for styling the career card

---

package-lock.json
public/scss/_help.scss
public/scss/style.scss
src/components/help.jsx

Relates #42
Add style to page and imported it in style.scss file
Apologies for the branch name. I opened it to work on the details but at the end worked first on the help page... :wink:

Add style to help page

---

src/containers/detail.jsx
src/containers/list.jsx
src/containers/welcome.jsx

relates #67 
Changed the CamelCase problems where I could see them
Also removed a couple of linter errors

CamelCase and linter

---

database/career_model.js
src/components/career_detail.jsx

Relates #74 
Add job icons to use on list and detail pages

Add icon field to schema with icons to database

---

src/containers/career.jsx
src/logic/career.logic.js

Relates #102 
moving some logic functions to a separate file

Careerjsx refactor

---

src/containers/career.jsx

Finished browsing jobs
